### ISSUE TITLE
Brainstorming session 2

### ISSUE THREAD

**Issue by etters** [WomenPlusPlus/deploy-impact-21-inzone-a#13]
# Story

In the second brainstorming session we want to further collect ideas about the product.

# Depends on
-  #34 

# Subtasks
- [x] Set up Jamboard
- [x] Have the brainstorming session
- [x] Summarize session on Slack for non-attendees

**Comment by etters** [comment]
The result of the brainstorming session was shared on Slack with some explanations and ideas on how to proceed.
