### ISSUE TITLE
App concept and roadmap

### ISSUE THREAD

**Issue by etters** [WomenPlusPlus/deploy-impact-21-inzone-a#159]
# Story
As team InZone A we want to present all of our app ideas as a "blueprint" in the end, even if they did not make it into design or implementation, and therefore we need this app concept.

# Tasks
- [x] #205
- [x] #206
- [x] Team members fill Roadmap
- [x] Consolidate Roadmap and style
- [x] Incorporate app concept in Roadmap
- [x] Present roadmap in pitch
- [x] Include coordinator items into app concept
 
# Output
Continued work on the diagram.
Documentation started.

# Review

# Acceptance criteria

**Comment by etters** [comment]
There will be a "roadmap" for the final handover. All the new info from the PO meeting 13/11 will be incorporated first, then moving from the concept to the roadmap.

**Comment by ebaumhofer** [comment]
@etters what can I do to help you with this?
