### ISSUE TITLE
Plan bi-weekly dates with PO

### ISSUE THREAD

**Issue by etters** [WomenPlusPlus/deploy-impact-21-inzone-a#16]
# Story
As team InZone A we want to use all opportunities to meet with the PO to get his feedback, ask questions and pitch ideas.

# Depends on
- #35
- Spring review/retro/planning for Sprint 5
- Spring review/retro/planning for Sprint 6

# Subtasks
- [x] Discuss whether to have these meetings before or after our sprint meeting of that weekend
- [x] Meeting 1 (around October 30)
- [x] Meeting 2 (around November 13)
- [x] Meeting 3 (around November 20)
