### ISSUE TITLE
3rd Meeting with UX mentor

### ISSUE THREAD

**Issue by Fotini-Handra** [WomenPlusPlus/deploy-impact-21-inzone-a#184]
# Subtasks

- [x] Plan meeting on agorize
- [x] Prepare a few slides with progress this far
- [x] Have meeting
- [x] Summary for team
