### ISSUE TITLE
Competitors Research

### ISSUE THREAD

**Issue by mannar-hielal** [WomenPlusPlus/deploy-impact-21-inzone-a#2]
As team InZone A we need to assess the relative strengths or weaknesses of competitors' products and services so that we are able to improve our design solution as well as product offerings. 

# Subtasks

- [x] Create competitive analysis guide on google drive
- [ ] Identify direct competitors 
- [ ] Identify analogous competitors 
- [ ] Decide which method to use for Competitive Analysis
   - [ ] Plus/ Delta (pros and cons)
   - [ ] Task Analysis
   - [ ] Feature Inventory
