### ISSUE TITLE
Define User Journey

### ISSUE THREAD

**Issue by mannar-hielal** [WomenPlusPlus/deploy-impact-21-inzone-a#5]
**subtasks**

- [x] create issue
- [ ] define all subtasks
- [ ] create template (technically)
- [ ] set stages and steps (horizontally)
- [ ] decide for which personas/mindsets to create a user journey
- [ ] for each persona/mindset
   - [ ] fill touchpoints, do/think/feel (vertically)
   - [ ] add emotions, pains and needs
   - [ ] identify opportunities
